---
- name: Create kafka group
  group:
    name: '{{ kafka_group }}'
    state: present

- name: Create kafka user
  user:
    name: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    state: present
    createhome: no

- name: Create kafka config dir
  file:
    path: "{{ kafka_conf_dir }}"
    state: directory
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: '0755'

- import_tasks: sasl-auth.yml
  tags: [kafka, kafka_config, config, sasl, auth]

- name: Create kafka server properties file
  template:
    src: server.properties.j2
    dest: "{{ kafka_conf_dir }}/server.properties"
    owner: '{{ kafka_user }}'
    group: '{{ kafka_group }}'
    mode: '0644'
  notify: Reload kafka
