---
  - name: Create JAAS configuration for Kafka broker
    template:
      src: kafka_server_jaas.conf.j2
      dest: "{{ kafka_conf_dir }}/kafka_server_jaas.conf"
      owner: '{{ kafka_user }}'
      group: '{{ kafka_group }}'
      mode: '0644'
    notify: Reload kafka

  - name: Add to kafka_environment_variables variable if it already exists
    set_fact:
      kafka_environment_variables: "{{ kafka_environment_variables | combine({'KAFKA_OPTS': '-Djava.security.auth.login.config=' + kafka_conf_dir + '/kafka_server_jaas.conf'}) }}"
    when: kafka_environment_variables is defined

  - name: Set fresh kafka_environment_variables variable if it does not exist
    set_fact:
      kafka_environment_variables:
        KAFKA_OPTS: "-Djava.security.auth.login.config={{ kafka_conf_dir }}/kafka_server_jaas.conf"
    when: kafka_environment_variables is not defined

  - name: Set Kafka listeners variable
    set_fact:
      kafka_listeners: "PLAINTEXT://{{ inventory_hostname }}:9092"
    when: kafka_listeners is not defined

  - name: Set Kafka inter-broker communication protocol
    set_fact:
      kafka_security_inter_broker_protocol: "PLAINTEXT"
    when: kafka_security_inter_broker_protocol is not defined

  - name: Set SASL mechanism for Kafka inter-broker communication protocol
    set_fact:
      kafka_sasl_mechanism_inter_broker_protocol: "PLAIN"
    when: kafka_sasl_mechanism_inter_broker_protocol is not defined

  - name: Set enabled SASL mechanisms for Kafka
    set_fact:
      kafka_sasl_enabled_mechanisms: "PLAIN"
    when: kafka_sasl_enabled_mechanisms is not defined
