---
- name: Verify kafka installation
  hosts: all
  tasks:
    - name: Gather facts on listening ports
      listen_ports_facts:
    - name: Create list of listening ports
      set_fact:
        tcp_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"
    - name: Verify kafka port is in listening ports
      assert:
        that:
          - 9092 in tcp_ports
    - name: Verify JMX port is in listening ports
      assert:
        that:
          - 1099 in tcp_ports
