---
- name: Install required roles
  hosts: all
  roles:
    - nl2go.openjdk

- name: Install ZooKeeper
  hosts: zookeeper
  vars:
    zookeeper_members: "{{ groups['zookeeper'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
  roles:
    - nl2go.zookeeper
