---
- name: Verify kafka installation
  hosts: all
  tasks:
    - name: Gather facts on listening ports
      listen_ports_facts:
    - name: Create list of listening ports
      set_fact:
        tcp_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"
    - name: Verify kafka port is in listening ports
      assert:
        that:
          - 9092 in tcp_ports
    - name: Check that kafka log file exists
      stat:
        path: /var/log/kafka/kafka.log
      register: stat_log_result
      failed_when: not stat_log_result.stat.exists
    - name: Add a topic to the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --create --bootstrap-server {{ inventory_hostname }}:9092 --replication-factor 1 --partitions 1 --topic test_default
      register: create_topic_result
    - name: Verify topic creation return code
      assert:
        that:
          - create_topic_result.rc == 0
    - name: Verify topic creation output
      assert:
        that:
          - "'Created topic test_default' in create_topic_result.stdout"
    - name: List topics from the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server {{ inventory_hostname }}:9092
      register: list_topics_result
    - name: Verify topic listing return code
      assert:
        that:
          - list_topics_result.rc == 0
    - name: Verify created topic is in topic list
      assert:
        that:
          - "'test_default' in list_topics_result.stdout"
