---
- name: Verify kafka installation
  hosts: kafka
  tasks:
    - name: Create random topic name
      set_fact:
        topic_name: "{{ 9999999999999999999999 | random | to_uuid }}"
      run_once: yes
    - name: Gather facts on listening ports
      listen_ports_facts:
    - name: Create list of listening ports
      set_fact:
        tcp_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"
    - name: Verify kafka port is in listening ports
      assert:
        that:
          - 9092 in tcp_ports
    - name: Check that kafka log file exists
      stat:
        path: /var/log/kafka/kafka.log
      register: stat_log_result
      failed_when: not stat_log_result.stat.exists
    - name: Add a topic to the kafka server
      command: "/usr/local/kafka/bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 3 --partitions 1 --topic {{ topic_name }}"
      register: create_topic_result
      run_once: yes
    - name: Verify topic creation return code
      assert:
        that:
          - create_topic_result.rc == 0
    - name: Verify topic creation output
      assert:
        that:
          - "'Created topic {{ topic_name }}' in create_topic_result.stdout"
    - name: List topics from the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
      register: list_topics_result
      changed_when: no
    - name: Verify topic listing return code
      assert:
        that:
          - list_topics_result.rc == 0
    - name: Verify created topic is in topic list
      assert:
        that:
          - "'{{ topic_name }}' in list_topics_result.stdout"
