---
- name: Create random topic name
  set_fact:
    topic_name: "{{ 9999999999999999999999 | random | to_uuid }}"
  run_once: yes
- name: Add a topic to the Kafka server
  environment:
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ kafka_conf_dir }}/jaas.cfg"
  command: "/usr/local/kafka/bin/kafka-topics.sh \
    --create --bootstrap-server {{ kafka_host }}:9092 --replication-factor 3 --partitions 1 --topic {{ topic_name }} \
    --command-config {{ kafka_test_client_conf }}"
  register: create_topic_result
  run_once: yes
- name: Verify topic creation return code
  assert:
    that:
      - create_topic_result.rc == 0
- name: Verify topic creation output
  assert:
    that:
      - "'Created topic {{ topic_name }}' in create_topic_result.stdout"
- name: List topics from the Kafka server
  environment:
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ kafka_conf_dir }}/jaas.cfg"
  command: "/usr/local/kafka/bin/kafka-topics.sh \
    --list --bootstrap-server {{ kafka_host }}:9092 \
    --command-config {{ kafka_test_client_conf }}"
  register: list_topics_result
  changed_when: no
- name: Verify topic listing return code
  assert:
    that:
      - list_topics_result.rc == 0
- name: Verify created topic is in topic list
  assert:
    that:
      - "'{{ topic_name }}' in list_topics_result.stdout"
