---
- name: Test JMX connection without authentication
  shell: echo "exit" | java -jar /opt/jmxterm.jar -l {{ kafka_jmx_host }}:1099
  register: jmx_status_noauth
  changed_when: no
  failed_when: jmx_status_noauth.rc != 1
- name: Test JMX connection with authentication
  shell: echo "exit" | java -jar /opt/jmxterm.jar -l {{ kafka_jmx_host }}:1099 -u jmx -p molecule
  register: jmx_status_auth
  changed_when: no
- name: Verify JMX connection
  assert:
    that:
      - "'Welcome to JMX terminal' in jmx_status_auth.stderr"
