---
- name: Cleanup test resources
  hosts: localhost
  tasks:
    - name: Stop zookeeper container
      docker_container:
        name: zookeeper
        image: confluentinc/cp-zookeeper:5.5.0
        state: stopped
        purge_networks: yes
      delegate_to: localhost
      run_once: true
