---
- name: Verify kafka installation
  hosts: all
  tasks:
    - name: Gather facts on listening ports
      listen_ports_facts:
    - name: Create list of listening ports
      set_fact:
        tcp_ports: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"
    - name: Verify kafka port is in listening ports
      assert:
        that:
          - 9092 in tcp_ports
    - name: Check that kafka log file exists
      stat:
        path: /var/log/kafka/kafka.log
      register: stat_log_result
      failed_when: not stat_log_result.stat.exists

- name: Verify kafka cluster installation on broker1
  hosts: broker1
  tasks:
    - name: Add a topic to the kafka server with replication factor 3
      command: /usr/local/kafka/bin/kafka-topics.sh --create --bootstrap-server broker1:9092,broker2:9092,broker3:9092 --replication-factor 3 --partitions 1 --topic test_cluster_topic
      register: create_topic_result
    - name: Verify topic creation return code
      assert:
        that:
          - create_topic_result.rc == 0
    - name: Verify topic creation output
      assert:
        that:
          - "'Created topic test_cluster_topic' in create_topic_result.stdout"
    - name: List topics from the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server broker1:9092,broker2:9092,broker3:9092
      register: list_topics_result
    - name: Verify topic listing return code
      assert:
        that:
          - list_topics_result.rc == 0
    - name: Verify created topic is in topic list
      assert:
        that:
          - "'test_cluster_topic' in list_topics_result.stdout"

- name: Verify kafka cluster installation on broker2
  hosts: broker2
  tasks:
    - name: List topics from the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server broker1:9092,broker2:9092,broker3:9092
      register: list_topics_result
    - name: Verify topic listing return code
      assert:
        that:
          - list_topics_result.rc == 0
    - name: Verify created topic is in topic list
      assert:
        that:

- name: Verify kafka cluster installation on broker3
  hosts: broker3
  tasks:
    - name: List topics from the kafka server
      command: /usr/local/kafka/bin/kafka-topics.sh --list --bootstrap-server broker1:9092,broker2:9092,broker3:9092
      register: list_topics_result
    - name: Verify topic listing return code
      assert:
        that:
          - list_topics_result.rc == 0
    - name: Verify created topic is in topic list
      assert:
        that:
          - "'test_cluster_topic' in list_topics_result.stdout"
